-- local defaults = require("nvchad.configs.lspconfig")
--
-- local function lsp_keymaps(client, bufnr)
--   local opts = { buffer = bufnr, remap = false }
--
--   -- defaults.on_attach(client, bufnr)
--
--   vim.keymap.set("n", "gd", vim.lsp.buf.definition, vim.tbl_extend("force", opts, { desc = "Go to definition" }))
--   vim.keymap.set("n", "gD", vim.lsp.buf.declaration, vim.tbl_extend("force", opts, { desc = "Go to declaration" }))
--   vim.keymap.set("n", "<leader>vt", vim.lsp.buf.type_definition, vim.tbl_extend("force", opts, { desc = "View type definition" }))
--   vim.keymap.set("n", "<leader>vr", vim.lsp.buf.references, vim.tbl_extend("force", opts, { desc = "View references" }))
--   vim.keymap.set("n", "K", vim.lsp.buf.hover, vim.tbl_extend("force", opts, { desc = "Hover documentation" }))
--
--   vim.keymap.set("n", "<leader>vd", vim.diagnostic.open_float, vim.tbl_extend("force", opts, { desc = "View diagnostics" }))
--   vim.keymap.set("n", "[d", vim.diagnostic.goto_prev, vim.tbl_extend("force", opts, { desc = "Go to previous diagnostic" }))
--   vim.keymap.set("n", "]d", vim.diagnostic.goto_next, vim.tbl_extend("force", opts, { desc = "Go to next diagnostic" }))
--
--   vim.keymap.set("n", "<leader>va", vim.lsp.buf.code_action, vim.tbl_extend("force", opts, { desc = "Code action" }))
--   vim.keymap.set("n", "<leader>vrn", require("nvchad.lsp.renamer"), vim.tbl_extend("force", opts, { desc = "Rename symbol" }))
--   vim.keymap.set("n", "<leader>vf", vim.lsp.buf.format, vim.tbl_extend("force", opts, { desc = "Format buffer" }))
--
--   vim.keymap.set("n", "<C-k>", vim.lsp.buf.signature_help, vim.tbl_extend("force", opts, { desc = "Signature Help" }))
--   vim.keymap.set("i", "<C-k>", vim.lsp.buf.signature_help, vim.tbl_extend("force", opts, { desc = "Signature Help" }))
-- end
--
-- vim.lsp.config("*", {
--   capabilities = defaults.capabilities,
--   on_attach = lsp_keymaps,
-- })
--
-- vim.lsp.config("gopls", {
--   capabilities = defaults.capabilities,
--   on_attach = lsp_keymaps,
--   settings = {
--     gopls = {
--       analyses = { unusedparams = true },
--       staticcheck = true,
--       gofumpt = true,
--     },
--   },
-- })
--
-- vim.lsp.enable({ "gopls", "lua_ls" }) 
